backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections: 
  - name: "prueba" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "prueba" # Used in the UI, ie.: "New Post"
    folder: "content/post/prueba" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titulo de post", name: "title", widget: "string"}
      - {label: "Publicar fecha", name: "date", widget: "datetime"}
      - {label: "Resumen", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}